export const ROLES = {
  SUPER_ADMIN: "super_admin",
  RESTAURANT_ADMIN: "restaurant_admin",
  MANAGER: "manager",
  WAITER: "waiter",
  KITCHEN: "kitchen_staff",
  CASHIER: "cashier",
  CUSTOMER: "customer",
};

export const ROLE_HIERARCHY = [
  ROLES.SUPER_ADMIN,
  ROLES.RESTAURANT_ADMIN,
  ROLES.MANAGER,
  ROLES.WAITER,
  ROLES.KITCHEN,
  ROLES.CASHIER,
  ROLES.CUSTOMER,
];

export const PERMISSIONS = {
  RESTAURANT_MANAGE: "restaurant:manage",
  BRANCH_MANAGE: "branch:manage",
  USER_MANAGE: "user:manage",
  MENU_MANAGE: "menu:manage",
  TABLE_MANAGE: "table:manage",
  ORDER_CREATE: "order:create",
  ORDER_UPDATE: "order:update",
  ORDER_VIEW: "order:view",
  KITCHEN_MANAGE: "kitchen:manage",
  PAYMENT_PROCESS: "payment:process",
  INVENTORY_MANAGE: "inventory:manage",
  EMPLOYEE_MANAGE: "employee:manage",
  PAYROLL_MANAGE: "payroll:manage",
  REPORT_VIEW: "report:view",
  EXPENSE_MANAGE: "expense:manage",
  COUPON_MANAGE: "coupon:manage",
  RESERVATION_MANAGE: "reservation:manage",
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.RESTAURANT_ADMIN]: Object.values(PERMISSIONS).filter(
    (p) => p !== PERMISSIONS.RESTAURANT_MANAGE
  ),
  [ROLES.MANAGER]: [
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.TABLE_MANAGE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.EMPLOYEE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.EXPENSE_MANAGE,
    PERMISSIONS.RESERVATION_MANAGE,
    PERMISSIONS.COUPON_MANAGE,
  ],
  [ROLES.WAITER]: [
    PERMISSIONS.TABLE_MANAGE,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_VIEW,
  ],
  [ROLES.KITCHEN]: [PERMISSIONS.KITCHEN_MANAGE, PERMISSIONS.ORDER_VIEW],
  [ROLES.CASHIER]: [
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
  ],
  [ROLES.CUSTOMER]: [PERMISSIONS.ORDER_CREATE, PERMISSIONS.ORDER_VIEW],
};
